services:
  web:
    build: .
    # O Caddy vai conversar com o web pela porta 5000 internamente.
    # Se sua aplicação roda na 5000, não precisamos expor portas aqui 
    # para o mundo externo, o Caddy cuidará disso.
    expose:
      - "5000"
    environment:
      - DJANGO_SECRET_KEY=${"DJANGO_SECRET_KEY", os.getenv("DJANGO_SECRET_KEY")}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}
    restart: always
    networks:
      - aaleff_network
    volumes:
      - static_volume:/app/staticfiles
      - db_volume:/app/db_data

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - static_volume:/var/www/static:ro
    networks:
      - aaleff_network
    depends_on:
      - web

networks:
  aaleff_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  static_volume:
  db_volume: