# Generated by Django 5.1.15 on 2026-03-10 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='Navegador/Dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=20, unique=True, verbose_name='Número do Protocolo')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início do Atendimento')),
                ('consentimento_lgpd', models.BooleanField(default=False, verbose_name='Aceitou Termos?')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.CharField(choices=[('user', 'Usuário'), ('bot', 'AIWA Bot')], max_length=10)),
                ('texto', models.TextField()),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat.sessao')),
            ],
        ),
    ]
