# Generated by Django 5.1.15 on 2026-03-11 13:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='Navegador/Dispositivo')),
            ],
            options={
                'verbose_name': 'Acesso',
                'verbose_name_plural': 'Acessos',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='ProvedorIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Provedor (ex: OpenAI, Google)')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo (ex: gpt-4o)')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
            ],
            options={
                'verbose_name': 'Provedor de IA',
                'verbose_name_plural': '🔗 Provedores de IA',
            },
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=20, unique=True, verbose_name='Número do Protocolo')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início do Atendimento')),
                ('consentimento_lgpd', models.BooleanField(default=False, verbose_name='Aceitou Termos?')),
            ],
            options={
                'verbose_name': 'Sessão de Chat',
                'verbose_name_plural': 'Sessões de Chat',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Agente')),
                ('system_prompt', models.TextField(help_text='Aja como... Seu objetivo é...', verbose_name='System Prompt')),
                ('temperatura', models.FloatField(default=0.7, help_text='0.0 (Focado/Rígido) a 1.0 (Muito Criativo)')),
                ('provedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.provedoria', verbose_name='Provedor')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': '🤖 Agentes de IA',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.CharField(choices=[('user', 'Usuário'), ('bot', 'AIWA Bot')], max_length=10)),
                ('texto', models.TextField()),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat.sessao')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': '💬 Mensagens',
            },
        ),
    ]
