# Generated by Django 5.1.15 on 2026-03-10 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvedorIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Provedor (ex: OpenAI, Google)')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo (ex: gpt-4o)')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
            ],
            options={
                'verbose_name': 'Provedor de IA',
                'verbose_name_plural': 'Provedores de IA',
            },
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Agente')),
                ('system_prompt', models.TextField(help_text='Aja como... Seu objetivo é...', verbose_name='System Prompt')),
                ('temperatura', models.FloatField(default=0.7, help_text='0.0 (Focado/Rígido) a 1.0 (Muito Criativo)')),
                ('provedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.provedoria', verbose_name='Provedor')),
            ],
        ),
    ]
