name: Deploy to DigitalOcean Droplet

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            mkdir -p ~/app
            cd ~/app

            # Lógica de Git: Força a sincronia com o novo histórico
            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }}.git .
            else
              git fetch origin main
              git reset --hard origin/main
            fi

            # Limpeza de containers antigos
            docker stop $(docker ps -q) 2>/dev/null || true
            docker rm $(docker ps -aq) 2>/dev/null || true

            # Sobe a aplicação
            # Nota: O comando migrate agora roda sem comentários na linha
            docker compose run -e DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} web python manage.py migrate
            docker compose down
            docker compose up -d --build

            docker image prune -f